### ISSUE TITLE
Croatoan is installed and loaded but unusable (functions are undefined)

### ISSUE THREAD

**Issue by Kunderscore** [McParen/croatoan#10]
```
* To load "croatoan":
  Load 1 ASDF system:
    croatoan
; Loading "croatoan"

; in: DEFUN T03C
;     (CLEAR SCR)
; 
; caught STYLE-WARNING:
;   undefined function: CLEAR

;     (REFRESH SCR)
; 
; caught STYLE-WARNING:
;   undefined function: REFRESH

;     (SCR :INPUT-ECHOING NIL :INPUT-BLOCKING T)
; 
; caught STYLE-WARNING:
;   undefined function: SCR

;     (WITH-SCREEN (SCR :INPUT-ECHOING NIL :INPUT-BLOCKING T) (CLEAR SCR)
;      (PRINC "Type chars. Type q to quit." SCR) (REFRESH SCR)
;      (LOOP FOR CH = (READ-CHAR SCR)
;            WHILE (NOT (EQUAL CH #\q))
;            DO (PRINC CH SCR))
;      (PRINC "You pressed q. Now press any char to quit." SCR) (READ-CHAR SCR))
; 
; caught STYLE-WARNING:
;   undefined function: WITH-SCREEN
; 
; compilation unit finished
;   Undefined functions:
;     CLEAR REFRESH SCR WITH-SCREEN
;   caught 4 STYLE-WARNING conditions
```
This is produced by evaluating the following code in emacs + slime, test t03c, with my code as follow
```
(ql:quickload :croatoan)

(defparameter scr nil)
(defun t03c ()
  (with-screen (scr :input-echoing nil :input-blocking t)
    (clear scr)
    (princ "Type chars. Type q to quit." scr)
    (refresh scr)

    (loop for ch = (read-char scr)
       while (not (equal ch #\q))
       do (princ ch scr))

    (princ "You pressed q. Now press any char to quit." scr)
    (read-char scr)))
```

**Comment by McParen** [comment]
Hello Kunderscore, thanks for checking out the library. 

When you start SLIME, you are by default in the "CL-USER" package. While "ql:quickload" fetches, compiles and loads the system "croatoan", it does not automatically enter the croatoan package.

You can either do `(in-package :croatoan)` before any code, or prepend any function separately with the package qualifier like `(croatoan:with-screen (scr) ... )`, or `:use` the package or `:import-from` single symbols in a `asd` file.

Also since croatoan uses ncurses under the hood, and ncurses speaks to the underlying terminal, you will not be able to test any terminal-based code in SLIME directly, because SLIME's/Emacs' support for terminal control codes is very limited.

**Comment by Kunderscore** [comment]
ahh, that makes sense
how stupid of me
will try out immediately

**Comment by veddox** [comment]
```
(let ((h (.height scr)) (w (.width scr))
    (<body>))
```
gives you the screen height in the `h` variable and the width in `w`.

Here is the Croatoan documentation: http://quickdocs.org/croatoan/api#package-DE.ANVI.CROATOAN (Not quite up-to-date, but mostly accurate.)

**Comment by veddox** [comment]
It's hard to know what the problem is without seeing your code...

But a Github issue thread is also not really the right place for programming help. I suggest you ask the folks on IRC (on the #lisp channel), I've found them to be quite helpful. Or perhaps on Reddit: https://www.reddit.com/r/lisp.

If there is a genuine resource-usage problem with croatoan, then you should open another issue thread for that.

**Comment by McParen** [comment]
Hello Kunderscore,

> but it seems to have the same effect, i.e 100% cpu usage

The 100% CPU usage only occurs in cases where :input-blocking is nil (example t03a). You can either set blocking to t, or sleep for a short time on each loop cycle, like in example t13.

**Comment by Kunderscore** [comment]
Thank you very much for your time!
Im sorry for the trouble by using github issue as a programming help.

But would enable input-blocking cause program freezes? (which is why i set it to nil, like you said)

**Comment by veddox** [comment]
Whenever the user presses a key, croatoan generates an event that is fed into the program's event-loop. However, as long as input-blocking is not `T`, croatoan also generates events when the user doesn't do anything - this is the `(nil)` event. By specifying `:input-blocking nil`, you are telling croatoan to continuously generate new `(nil)` events as long as your window is not busy processing something else. From the `event-case` documentation:

> If input-blocking is t, the (nil) event is never returned.
> Instead of ((nil) nil), which eats 100% CPU, use input-blocking t.

If you need the `(nil)` event to update the window even while the user is idle, but don't want a continuous stream of events, you can set input-blocking to a millisecond integer value to set the frequency with which it is generated.

For a simple tutorial that uses croatoan (and input-blocking), see [here](https://terranostra.one/posts/ASCII-Art-Animations-in-Lisp.html).
