### ISSUE TITLE
Missing a way to check if a window was deleted

### ISSUE THREAD

**Issue by D4ryus** [McParen/croatoan#13]
There seems to be no way to check if `close` (`%delwin`) was called on a window.
As a workaround i wrap `window` and set `winptr` to `nil` when `close` is called. As this is a common use case, it would be a nice feature if it was added to croatoan.

**Comment by McParen** [comment]
Hello,

the gray streams interface which allows windows to be treated as streams allows you to use the standard function "open-stream-p":

_"It is true if its argument (which must be a stream) is open, and otherwise is false. A stream is always created open; it remains open until closed with the close function."_

Which is exactly what youre looking for.

Sadly, it does not work in the current code yet. I never used open-stream-p myself before, so I have not tested it properly. Fortunately, it seems to be very easy to fix, and I will push the fix to the repository in the next few days.

**Comment by D4ryus** [comment]
Sounds good, thank you!

**Comment by McParen** [comment]
close now sets a flag for open-stream-p to test whether windows have been closed.

It for now works only for window objects, not for its subclasses. I have to look more closely how to pass this flag to the subclasses efficiently.
