### ISSUE TITLE
True color terminals and alternate character set

### ISSUE THREAD

**Issue by stacksmith** [McParen/croatoan#3]
I am running xterm and st terminals with TERM=xterm-256color.

Possibly because of that I am unable to see any ACS characters (they come out as q's and such).  Have you any thoughts on how to fix that?

**Comment by McParen** [comment]
The ACS chars are loaded at run time by ncurses. Whether it works or not, depends on the ncurses version used, the sbcl implementation used, on the terminal used, etc.

In short, it is quite complex, and I have limited myself to make it work on the combination I am using (xterm/gnome-terminal, sbcl, ncurses 5.9 and 6.0, single-byte and wide).

I could not repeat your problem when running the ACS tests t12-t12c with TERM=xterm-256color on my system.

Can you specify what system (32/64 bit, lisp implementation, ncurses version) you are using?

I have tried to run croatoan on CCL a few times, and the ACS chars were the first thing that did not work.

For xterm-256color to actually work, ncurses has to be compiled with --enable-ext-colors, the default is 16 colors. I havent tested the 256 color mode yet because the major distributions do not distribute ncurses that way, and it also would change the ncurses ABI.

**Comment by stacksmith** [comment]
Sorry, here is my system infor:
xubuntu 16.04
ncurses 6.0
sbcl 1.3.12
 I get the same (unfortunate) results on xfce4-terminal 0.6.3 and suckless' st.  
I don't remeber recompiling ncurses, but i definitely get 256 colors and truecolor.  I did have to add TERM=xterm-256color by hand.  Number of colors and color-pairs is definitely >8 and 64. I think both are 256.

**Comment by McParen** [comment]
I have tried to replicate your bug on my two ubuntu systems, 12.04 and 16.04, both 64bit, sbcl 1.3.12 and 1.3.15, xterm and gnome-terminal, with ncurses 5.9 and 6.0, char and wide-char versions, 8 colors and 256 colors, and not a single combination had problem with AS chars.

At the moment, I have no idea where your bug might come from.

But you were right with one thing, Ubuntu apparently does provide 256-color enabled ncurses by default, not just the basic 8-color version, so I will have to modify croatoan to reflect this.

If you manage to find out how your bug was caused, and it is something I can prevent, please let me know.

**Comment by stacksmith** [comment]
Thank you for your help!  I will investigate more.  I've been searching for a solution to another problem for a while now, and have installed a bunch of software on my machine so it is possible it is no longer a 'stock' system.  I will let you know if I find anything important.

BTW, I was wrong about xfce4-terminal truecolor support out of the box.  st does support truecolor escapes.

**Comment by McParen** [comment]
In the meantime, I have also tried running the ACS examples with st and its terminfo. Since there has been no way to replicate this bug, I am closing this issue now.

Also the stock ncurses built by ubuntu and apparently debian do not provide 256 color support, according to the build logs on lunchpad. They explicitely build with API 5.
