### ISSUE TITLE
support for 24bit color

### ISSUE THREAD

**Issue by cage2** [McParen/croatoan#33]
Hi McParen,

i would like to use the 24bit RGB color on my application but i think the library coerce the 8 bit color to 6 bit color even if the terminal support color specified as 8 bit per channel.

I wonder if checking if a terminal support 24bit color and bypass the conversion 8bit to 6bit could suffice.

I have found this document to checks if a terminal support 24bit colors

https://gist.github.com/XVilka/8346728#true-color-detection

it is not perfect but should not give false positive, at least.

What do you think?

Bye!
C.

**Comment by McParen** [comment]
Hello,

ncurses does as far as I know not limit the depth of single colors that can be used. You can address any 24bit color by redefining colors in the standard 256color palette.

What ncurses does not allow is passing the RGB components directly, as can be done with the ansi escape sequences 38;2;R;G;Bm and 48;2;R;G;Bm on some terminals. You still have to use the "color numbers", but since ncurses 6.1 4byte int can be used for colors and color pairs (allowing for millions of simultaneously used) instead of signed short which was the default till ncurses 6.1, where you were limited to at max 32768 color pairs.

So if you do not need the 16 millions colors at the same time, the extended colors interface sounds sufficient.

**Comment by cage2** [comment]
On Fri, Apr 17, 2020 at 02:20:03AM -0700, McParen wrote:
> Hello,

Hi!

>
> ncurses does as far as I know not limit the depth of single colors that can be used. You can address any 24bit color by redefining colors in the standard 256color palette.
>
> What ncurses does not allow is passing the RGB components directly, as can be done with the ansi escape sequences 38;2;R;G;Bm and 48;2;R;G;Bm on some terminals. You still have to use the "color numbers", but since ncurses 6.1 4byte int can be used for colors and color pairs (allowing for millions of simultaneously used) instead of signed short which was the default till ncurses 6.1, where you were limited to at max 32768 color pairs.

Ok i think i am staring to understand, so you suggest something like:

; -----

(init-extended-color +color-black+ 1000    0 1000)
(init-extended-color +color-red+   1000 1000    0)
(init-pair 1 +color-black+ +color-red+)
(attron (color-pair 1))
;; print a string with low-level interface
(attroff (color-pair 1))

; ------

right?

Thank you!
C.

**Comment by McParen** [comment]
You do not have to use attron and other low-level color routines to actually use and display the colors, just to redefine the color numbers in the standard palette. After the individual colors are redefined, you use them just as you would use the predefined colors, i.e. you can use the high level interface for that.

In the high level interface, the palette color numbers can be passed as a name like :black or as a list list (:number 0) to directly pass its color number. 

Since the first 8 (or 16 in the 265 color mode) colors are named, it makes no sense to redefine them, because at the moment the names cant be easily reassigned, but the colors above that can be redefined as needed.

In the long run, I want to be able to pass any color as simply as giving its hex code, either as a string "#FF0000" or as a lisp integer #xff0000, but I've yet to work on that.

**Comment by cage2** [comment]
On Fri, Apr 17, 2020 at 11:50:18AM -0700, McParen wrote:

Hi McParen!

> You do not have to use  attron and other low-level color routines to
> actually  use and  display the  colors, just  to redefine  the color
> numbers in  the standard  palette. After  the individual  colors are
> redefined, you use them just as you would use the predefined colors,
> i.e. you can use the high level interface for that.
>
> In the high level interface, the palette color numbers can be passed as a name like :black or as a list list (:number 0) to directly pass its color number.

Wow, that's great! Makes the things much simpler!

>  In the long run,  I want to be able to pass any  color as simply as
> giving  its hex  code, either  as a  string "#FF0000"  or as  a lisp
> integer #xff0000, but I've yet to work on that.

Well i think the code you wrote is a already a lot!

Thank you McParen  i hope i will  succeed and be able to  show you the
results of this discussion!

Bye!
C.

**Comment by McParen** [comment]
Hello, I had to edit my previous comment. To some degree, you are right, but until you can limit yourself to roughly 16000 colors that fit into a signed short int, you dont have to use the extended functions.

**Comment by cage2** [comment]
On Fri, Apr 17, 2020 at 12:26:41PM -0700, McParen wrote:
> Hello,

Hi McParen!

> I had  to edit my previous  comment. To some degree,  you are right,
>but until  you can limit  yourself to  roughly 16000 colors  that fit
>into a signed short int, you dont have to use the extended functions.

No problem, this means that i am  going to use the low-level API as in
my second post: i think it could be a fun exploration! :)

Bye!
C.
