### ISSUE TITLE
Last char drawn to menu choice to not be last char of string

### ISSUE THREAD

**Issue by Mr-X-666** [McParen/croatoan#39]
Instead of drawing the last char of the choice string to the choice, why not draw something like .. or give a choice to what the last char drawn will be so that menu choices will look better.

**Comment by McParen** [comment]
Hello, adding an ellipsis or some other truncation string to long menu item titles sounds useful.  I've had that on my TODO list since cage added the function text-ellipsize a while ago, but I havent got down to implement it yet.

**Comment by McParen** [comment]
It's been a while since this issue was opened, but I guess better late than never...

With the commit [a243d7a](https://github.com/McParen/croatoan/commit/a243d7a9a80cfdb84f69d70893af8ed14bfc0e04) menu item titles longer than max-item-length (default 15) are now by default ellipsized by the unicode ellipsis character "...". An alternative string can be passed with the initarg `:ellipsis "xyz"`. Passing an empty string truncates the item title at max-item-length.

McP
