### ISSUE TITLE
Foreign library definitions missing for MS Windows

### ISSUE THREAD

**Issue by Symbolics** [McParen/croatoan#43]
There is no curses library definition for MS Windows, so the build fails.

**Comment by McParen** [comment]
Hello Symbolics, thanks for the addition. The reason I did not add windows libraries to the list is that I do not have access to Windows, so I can not test any of these additions. The same applies to Macs, but a few years ago Mac support was added by a user. 

Also this library particularly targets ncurses and its extensions, not curses in general, so I also do not know whether pdcurses  loads at all or fails because of the missing ncurses extensions. Can you confirm, for example with screenshots, that some of the examples work at all under windows?

**Comment by Symbolics** [comment]
The examples run. [According to the author of ncurses](https://stackoverflow.com/questions/45558989/does-pdcurses-and-ncurses-have-the-same-syntax), pdcurses and ncurses are 'largely compatible'.

**Comment by McParen** [comment]
Hello Symbolics, I've pushed your commit, thanks. I've also added another name, libncursesw6, which is how it is provided by the official MinGW port, and prioritized them over the pdcurses entry. It would be nice if you at some point summarized what works on windows and what doesn't, so we can improve the windows bindings.
