### ISSUE TITLE
Tags and releases

### ISSUE THREAD

**Issue by Hellseher** [McParen/croatoan#49]
Hi,

I know it's not too common to use versioned tags and releases among Common Lisp projects but it would help to improve package distribution via Guix where it's pined to the latest commit which is not convenient to keep up-to-date.

How hard would it be to use versioned tag for the project?

Thanks,
Oleg

**Comment by McParen** [comment]
Hello Oleg,

thanks for taking interest in the library and making it available through Guix. Adding versioned tags would not be an issue at all, but the situation is that the library has not had any official releases yet. The library is still in development and since it was not packaged by any distro before and the current users (most notably cage/tinmop) have not expressed a wish to have the library versioned in its current state, I have not been doing it yet. I do plan to make actual releases, but at some point in the future, where I am more certain that the external API will not change.

While I could produce tagged releases, I would not do that for every commit, so the tagged releases would cease to be up-to-date after a while. I have not used Guix yet, so I do not know what its usual release cycles are. How often should a package be updated with a version bump to be in sync with the Guix ecosystem?

Regards,
McP

**Comment by wmealing** [comment]
McParen.. just a heads up.. there are many more silent like myself that appreciate your work.  We may not have a lot to say but we are users.  

Don't feel like that you're alone on this project, because there are many of us silent who are appreciative of your work.

**Comment by McParen** [comment]
Hello wmealing, thank you for your kind words. I'm aware of the silent users, it means a lot and you are not overlooked. :) Feel free to participate in any way you are comfortable with. McP.

**Comment by cage2** [comment]
Hi everyone!

I feel the needs to add my contribute to this thread as I think I am, someway, responsible  for the report and maybe is useful to explain why.

In fact i think I am the person that added croatoan to guix and keeps upgrading the package definition.

I tracks the development of croatoan and check if tinmop keeps working with the new version of this library. When tinmop is ready for a new release I update its package definition form and send the patch to the guix teams. Every time (minus the times I forgot it! :-( ), I also send a patch to upgrade croatoan to keeps the library in sync with the software.

I am sorry if this process broke some other person's workflow, to be honest I have not experienced a single API compatibility problem with croatoan in many months, i wrongly assumed was the same for others too.

As a partial solution, if it is useful and you agree, i could post on the project mailing list that I plan to upgrade the croatoan package definition, and wait for any objection.

Bye!
C.

**Comment by Hellseher** [comment]
Hi,

Thanks that this topic attracted your attention! As @cage2  mentioned there is no strict flow in Guix to have packages updated downstream it's rolling release anyway and trying to keep all dependencies in buildable state as much as possible.

And by having a version tag makes it easy to keep package update with one line of command like `guix refresh croatoan -u` without searching the latest commit upstream. For me personally version tag in general mean that the project reached sort of state where everybody may try to use it quite safely, but it's my personal feeling.

Thanks for your work.
Oleg.

**Comment by McParen** [comment]
Hello,

@cage2

thanks for submitting the library to guix! I wasnt aware that you are maintaining the package. I would tag a new minor 0.x version of the library 1-2 times a year if that would make syncing with tinmop and guix easier.

@Hellseher

Even though updating minor versions to pre-1.0 code does not really prevent breakage from an user pov, I can do that if it helps keeping track periodically, maybe 1-2 times a year, since updating guix for every commmit is certainly not necessary.

Take care,
McP

**Comment by cage2** [comment]
> Hello,

Hi McParen!

>  thanks for submitting  the library to guix! I wasnt  aware that you
> are maintaining the package.

You're welcome!

I have  to be  honest, I  have used  guix just  enough to  make tinmop
available,  but I  am very  happy  that my  work was  useful to  other
persons, this encourage me to keep working on packaging! :)

> I would tag a new minor 0.x  version of the library 1-2 times a year
> if that would make syncing with tinmop and guix easier.

I  have  not  had  any  problems keeping  in  sync  tinmop  with  your
development model so far  but if you decide to do  tag releases i will
stick (without issues)  with that when releasing  tinmop, because this
thread seems to show  that tagging is a good thing  to maintain a more
healthy  guix environment  and  expands the  opportunity  to use  this
library, and I am OK with both things! :)

Bye!
C.

**Comment by McParen** [comment]
Hello Hellseher, hello cage,

as Helleher recommended, I have added a first tagged release v0.1 to the repo today. I guesstimate that I will increment the version and make tagged releases once or twice a year, so I hope that's frequent enough to keep everything in sync.

Regards,
McP

**Comment by cage2** [comment]
Hi @McParen !

That's great! I will make the guix package to track tagged release then.

Bye!
C.

**Comment by McParen** [comment]
Hello cage, I've seen that your patch to the guix package has been now applied. Sincere thanks a lot for your support!
